FROM node:20

WORKDIR /app

COPY package*.json ./

RUN apt-get update && apt-get install -y python3 make g++ && \
    npm install --legacy-peer-deps && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
